@startuml en


entity Employee {
  *id : string
  --
  name : string
  position : string
  email : string
  hire_date : date
  phone_number : string
  store_id : string
}

entity Product {
  *id : string
  --
  name : string
  price : float
  category : string
  quantity : int
}

entity Store {
  *id : string
  --
  name : string
  address_id : string
  supplier_id : string
}

entity Address {
  *id : string
  --
  street : string
  city : string
  country : string
  postalCode : string
}

entity Supplier {
  *id : string
  --
  name : string
  contact_email : string
  phone : string
  address_id : string
}

Employee "n" -- "1" Store : employed-in
Store "1" -- "1" Address : located-at
Store "n" -- "1" Supplier : supplied-by
Store "n" -- "n" Product : sells
@enduml
