@startuml
package Deutschland {
    class Mitarbeiter {
        *mitarbeiterID: int
        --
        filialID: int
        name: string
        position: string
        mitarbeiterSeit: date
        gehalt: float
        email: string
        *filialID: int
    }
    
    class Produkt {
        *produktID: int
        --
        name: string
        kategorie: string
        preis: float
    }
    
    class Steuersatz {
        *steuersatzID: int
        --
        kategorie: string
        steuersatz: float
    }
    
    class ProduktVorOrt {
        *id: int
        --
        *produktID: int
        *filialID: int
        bestand: int
    }
    
    class Filiale {
        *filialID: int
        --
        standort: string
        manager: string
        oeffnungszeiten: string
    }

Produkt "1" -right- "*" ProduktVorOrt : hat
Filiale "1" -left- "*" ProduktVorOrt : istIn
Mitarbeiter "*" --o "1" Filiale : arbeitetIn
Produkt "*" --o "1" Steuersatz : hat


}
@enduml
